version: '3.8'

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=countries_db
    volumes:
      - ./rest_countries_db:/var/lib/postgresql/data:rw
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_TYPE: postgress
      MB_DB_DBNAME: countries_db
      MB_DB_PORT: 5432
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: pgdatabase
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - pgdatabase
    volumes:
      - ./rest_countries_db:/metabase-data
    ports:
      - "3000:3000"

  python_script:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - pgdatabase

volumes:
  rest_countries_db:
