version: '3'

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=countries_taxi
    volumes:
      - ./rest_countries:/var/lib/postgresql/data:rw
    ports:
      - "5431:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres:13
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: db_password
      MB_DB_HOST: pgdatabase
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - pgdatabase
    volumes:
      - dataviz_data:/metabase-data
    ports:
      - "3000:3000"

  python_script:
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  db_data:
  dataviz_data:
